locals {
  bgp_commands = [
    "set protocols bgp system-as ${var.fabric.defaults.bgp_system_as}",
    #"set protocols bgp parameters router-id ${var.router_id}",
    "set protocols bgp address-family l2vpn-evpn advertise-all-vni",
    "set protocols bgp address-family ipv6-unicast network fd69:255:240::11/128",
    "set protocols bgp address-family l2vpn-evpn flooding head-end-replication",
    "set protocols bgp address-family l2vpn-evpn vni 9002 rd '10.255.240.11:9002'",
    "set protocols bgp address-family l2vpn-evpn vni 9006 rd '10.255.240.11:9006'",
    "set protocols bgp address-family l2vpn-evpn vni 9008 rd '10.255.240.11:9008'",
    "set protocols bgp address-family l2vpn-evpn vni 9009 rd '10.255.240.11:9009'",
    "set protocols bgp address-family l2vpn-evpn vni 9010 rd '10.255.240.11:9010'",
    "set protocols bgp address-family l2vpn-evpn vni 9011 rd '10.255.240.11:9011'",
    "set protocols bgp neighbor eth1 interface v6only peer-group 'spine_underlay'",
    "set protocols bgp neighbor eth2 interface v6only peer-group 'spine_underlay'",
    "set protocols bgp neighbor fd69:255:240::1 peer-group 'spine_overlay'",
    "set protocols bgp neighbor fd69:255:240::2 peer-group 'spine_overlay'",
    "set protocols bgp parameters bestpath as-path multipath-relax",
    "set protocols bgp parameters fast-convergence",
    "set protocols bgp peer-group spine_overlay address-family l2vpn-evpn route-map export 'RM-EVPN-SPINE-EXPORT'",
    "set protocols bgp peer-group spine_overlay address-family l2vpn-evpn soft-reconfiguration inbound",
    "set protocols bgp peer-group spine_overlay bfd",
    "set protocols bgp peer-group spine_overlay remote-as 'internal'",
    "set protocols bgp peer-group spine_overlay update-source 'dum240'",
    "set protocols bgp peer-group spine_underlay address-family ipv6-unicast route-map export 'local_as_rm'",
    "set protocols bgp peer-group spine_underlay address-family ipv6-unicast soft-reconfiguration inbound",
    "set protocols bgp peer-group spine_underlay bfd",
    "set protocols bgp peer-group spine_underlay capability extended-nexthop",
    "set protocols bgp peer-group spine_underlay local-as 711 no-prepend replace-as",
    "set protocols bgp peer-group spine_underlay remote-as 'external'",
  ]
}
